window.digitalData = {
  offers: {
    o1: {
      pricePerMonth: "C$5.83",
      pricePerDeviceAfterCashback: "C$1.39",
      finalPriceAfterCashback: "C$69.99",
      pricePerYear: "C$69.99",
      finalPrice: "C$69.99",
      discountInPercent: "42%",
      pricePerYearAfterCashback: "C$69.99",
      unitOfMeasurementValue: "Years",
      uf: {
        pricePerYearAfterCashbackBeforeDecimal: "69",
        pricePerYearAfterDecimal: "99",
        pricePerMonth: "5.83",
        pricePerMonthAfterDecimal: "83",
        pricePerDeviceAfterCashback: "1.39",
        finalPriceAfterCashback: "69.99",
        finalPriceAfterCashbackAfterDecimal: "99",
        pricePerYear: "69.99",
        finalPrice: "69.99",
        discountInPercent: "42",
        pricePerYearAfterCashback: "69.99",
        pricePerMonthAfterCashbackAfterDecimal: "83",
        pricePerMonthBeforeDecimal: "5",
        totalCashbackAfterDecimal: "00",
        totalCashbackBeforeDecimal: "0",
        pricePerYearAfterCashbackAfterDecimal: "99",
        aRPriceAfterDecimal: "99",
        discountValueAfterDecimal: "00",
        pricePerDayAfterDecimal: "19",
        pricePerDayBeforeDecimal: "0",
        pricePerDayAfterCashbackBeforeDecimal: "0",
        aRPriceBeforeDecimal: "119",
        discountAmountAfterCashbackBeforeDecimal: "50",
        finalPriceBeforeDecimal: "69",
        pricePerDeviceAfterCashbackAfterDecimal: "39",
        pricePerYearBeforeDecimal: "69",
        retailPriceBeforeDecimal: "119",
        pricePerDeviceBeforeDecimal: "1",
        pricePerDeviceAfterDecimal: "39",
        pricePerDay: "0.19",
        discountAmountAfterCashback: "50.00",
        retailPriceAfterDecimal: "99",
        discountValueBeforeDecimal: "50",
        pricePerDevice: "1.39",
        finalPriceAfterCashbackBeforeDecimal: "69",
        discountAmountAfterCashbackAfterDecimal: "00",
        pricePerDayAfterCashbackAfterDecimal: "19",
        totalCashback: "0.00",
        pricePerMonthAfterCashback: "5.83",
        pricePerDayAfterCashback: "0.19",
        pricePerMonthAfterCashbackBeforeDecimal: "5",
        retailPrice: "119.99",
        finalPriceAfterDecimal: "99",
        discountValue: "50",
        aRPrice: "119.99",
        pricePerDeviceAfterCashbackBeforeDecimal: "1",
      },
      metaOfferTypeValue: "Standard",
      discountType: 1,
      affiliateCode: "global_1262",
      metaOfferType: 1,
      aRPackagePlan: {
        unitOfMeasurement: 3,
        planType: 3,
        planTypeValue: "Renew",
        unitOfMeasurementValue: "Years",
        isAutoRenewable: false,
        unitValue: 1,
      },
      unitValue: 1,
      unitOfMeasurement: 3,
      cultureCode: "EN-CA",
      planType: 2,
      discountTypeValue: "Amount",
      promotionalARPrice: "",
      metaOfferGuid: "A1F020CA-1CF0-4C4B-B301-AA135986D1F8",
      pricePerDay: "C$0.19",
      discountAmountAfterCashback: "C$50.00",
      pricePerDevice: "C$1.39",
      planTypeValue: "Paid",
      packageCode: "mls_430",
      totalCashback: "C$0.00",
      pricePerMonthAfterCashback: "C$5.83",
      pricePerDayAfterCashback: "C$0.19",
      planDescription: "1-Years-Paid",
      isAutoRenewable: true,
      retailPrice: "C$119.99",
      currencyCode: "CAD",
      discountValue: "C$50.00",
      aRPrice: "C$119.99",
    },
    o2: {
      pricePerMonth: "C$4.16",
      pricePerDeviceAfterCashback: "C$1.99",
      finalPriceAfterCashback: "C$99.99",
      pricePerYear: "C$49.99",
      finalPrice: "C$99.99",
      discountInPercent: "58%",
      pricePerYearAfterCashback: "C$49.99",
      unitOfMeasurementValue: "Years",
      uf: {
        pricePerYearAfterCashbackBeforeDecimal: "49",
        pricePerYearAfterDecimal: "99",
        pricePerMonth: "4.16",
        pricePerMonthAfterDecimal: "16",
        pricePerDeviceAfterCashback: "1.99",
        finalPriceAfterCashback: "99.99",
        finalPriceAfterCashbackAfterDecimal: "99",
        pricePerYear: "49.99",
        finalPrice: "99.99",
        discountInPercent: "58",
        pricePerYearAfterCashback: "49.99",
        pricePerMonthAfterCashbackAfterDecimal: "16",
        pricePerMonthBeforeDecimal: "4",
        totalCashbackAfterDecimal: "00",
        totalCashbackBeforeDecimal: "0",
        pricePerYearAfterCashbackAfterDecimal: "99",
        aRPriceAfterDecimal: "99",
        discountValueAfterDecimal: "00",
        pricePerDayAfterDecimal: "13",
        pricePerDayBeforeDecimal: "0",
        pricePerDayAfterCashbackBeforeDecimal: "0",
        aRPriceBeforeDecimal: "119",
        discountAmountAfterCashbackBeforeDecimal: "140",
        finalPriceBeforeDecimal: "99",
        pricePerDeviceAfterCashbackAfterDecimal: "99",
        pricePerYearBeforeDecimal: "49",
        retailPriceBeforeDecimal: "239",
        pricePerDeviceBeforeDecimal: "1",
        pricePerDeviceAfterDecimal: "99",
        pricePerDay: "0.13",
        discountAmountAfterCashback: "140.00",
        retailPriceAfterDecimal: "99",
        discountValueBeforeDecimal: "140",
        pricePerDevice: "1.99",
        finalPriceAfterCashbackBeforeDecimal: "99",
        discountAmountAfterCashbackAfterDecimal: "00",
        pricePerDayAfterCashbackAfterDecimal: "13",
        totalCashback: "0.00",
        pricePerMonthAfterCashback: "4.16",
        pricePerDayAfterCashback: "0.13",
        pricePerMonthAfterCashbackBeforeDecimal: "4",
        retailPrice: "239.99",
        finalPriceAfterDecimal: "99",
        discountValue: "140",
        aRPrice: "119.99",
        pricePerDeviceAfterCashbackBeforeDecimal: "1",
      },
      metaOfferTypeValue: "Standard",
      discountType: 1,
      affiliateCode: "global_1262",
      metaOfferType: 1,
      aRPackagePlan: {
        unitOfMeasurement: 3,
        planType: 3,
        planTypeValue: "Renew",
        unitOfMeasurementValue: "Years",
        isAutoRenewable: false,
        unitValue: 1,
      },
      unitValue: 2,
      unitOfMeasurement: 3,
      cultureCode: "EN-CA",
      planType: 2,
      discountTypeValue: "Amount",
      promotionalARPrice: "",
      metaOfferGuid: "183436B5-BF59-4D7E-949B-210AF6508F6F",
      pricePerDay: "C$0.13",
      discountAmountAfterCashback: "C$140.00",
      pricePerDevice: "C$1.99",
      planTypeValue: "Paid",
      packageCode: "mls_430",
      totalCashback: "C$0.00",
      pricePerMonthAfterCashback: "C$4.16",
      pricePerDayAfterCashback: "C$0.13",
      planDescription: "2-Years-Paid",
      isAutoRenewable: true,
      retailPrice: "C$239.99",
      currencyCode: "CAD",
      discountValue: "C$140.00",
      aRPrice: "C$119.99",
    },
    o3: {
      pricePerMonth: "C$2.08",
      pricePerDeviceAfterCashback: "C$0.49",
      finalPriceAfterCashback: "C$24.99",
      pricePerYear: "C$24.99",
      finalPrice: "C$24.99",
      discountInPercent: "79%",
      pricePerYearAfterCashback: "C$24.99",
      unitOfMeasurementValue: "Years",
      uf: {
        pricePerYearAfterCashbackBeforeDecimal: "24",
        pricePerYearAfterDecimal: "99",
        pricePerMonth: "2.08",
        pricePerMonthAfterDecimal: "08",
        pricePerDeviceAfterCashback: "0.49",
        finalPriceAfterCashback: "24.99",
        finalPriceAfterCashbackAfterDecimal: "99",
        pricePerYear: "24.99",
        finalPrice: "24.99",
        discountInPercent: "79",
        pricePerYearAfterCashback: "24.99",
        pricePerMonthAfterCashbackAfterDecimal: "08",
        pricePerMonthBeforeDecimal: "2",
        totalCashbackAfterDecimal: "00",
        totalCashbackBeforeDecimal: "0",
        pricePerYearAfterCashbackAfterDecimal: "99",
        aRPriceAfterDecimal: "99",
        discountValueAfterDecimal: "00",
        pricePerDayAfterDecimal: "06",
        pricePerDayBeforeDecimal: "0",
        pricePerDayAfterCashbackBeforeDecimal: "0",
        aRPriceBeforeDecimal: "119",
        discountAmountAfterCashbackBeforeDecimal: "95",
        finalPriceBeforeDecimal: "24",
        pricePerDeviceAfterCashbackAfterDecimal: "49",
        pricePerYearBeforeDecimal: "24",
        retailPriceBeforeDecimal: "119",
        pricePerDeviceBeforeDecimal: "0",
        pricePerDeviceAfterDecimal: "49",
        pricePerDay: "0.06",
        discountAmountAfterCashback: "95.00",
        retailPriceAfterDecimal: "99",
        discountValueBeforeDecimal: "95",
        pricePerDevice: "0.49",
        finalPriceAfterCashbackBeforeDecimal: "24",
        discountAmountAfterCashbackAfterDecimal: "00",
        pricePerDayAfterCashbackAfterDecimal: "06",
        totalCashback: "0.00",
        pricePerMonthAfterCashback: "2.08",
        pricePerDayAfterCashback: "0.06",
        pricePerMonthAfterCashbackBeforeDecimal: "2",
        retailPrice: "119.99",
        finalPriceAfterDecimal: "99",
        discountValue: "95",
        aRPrice: "119.99",
        pricePerDeviceAfterCashbackBeforeDecimal: "0",
      },
      metaOfferTypeValue: "Standard",
      discountType: 1,
      affiliateCode: "global_1262",
      metaOfferType: 1,
      aRPackagePlan: {
        unitOfMeasurement: 3,
        planType: 3,
        planTypeValue: "Renew",
        unitOfMeasurementValue: "Years",
        isAutoRenewable: false,
        unitValue: 1,
      },
      unitValue: 1,
      unitOfMeasurement: 3,
      cultureCode: "EN-CA",
      planType: 2,
      discountTypeValue: "Amount",
      promotionalARPrice: "",
      metaOfferGuid: "603C3ABD-DA95-4682-8348-1354381EDA22",
      pricePerDay: "C$0.06",
      discountAmountAfterCashback: "C$95.00",
      pricePerDevice: "C$0.49",
      planTypeValue: "Paid",
      packageCode: "mls_430",
      totalCashback: "C$0.00",
      pricePerMonthAfterCashback: "C$2.08",
      pricePerDayAfterCashback: "C$0.06",
      planDescription: "1-Years-Paid",
      isAutoRenewable: true,
      retailPrice: "C$119.99",
      currencyCode: "CAD",
      discountValue: "C$95.00",
      aRPrice: "C$119.99",
    },
    o4: {
      pricePerMonth: "C$4.16",
      pricePerDeviceAfterCashback: "C$49.99",
      finalPriceAfterCashback: "C$49.99",
      pricePerYear: "C$49.99",
      finalPrice: "C$49.99",
      discountInPercent: "38%",
      pricePerYearAfterCashback: "C$49.99",
      unitOfMeasurementValue: "Years",
      uf: {
        pricePerYearAfterCashbackBeforeDecimal: "49",
        pricePerYearAfterDecimal: "99",
        pricePerMonth: "4.16",
        pricePerMonthAfterDecimal: "16",
        pricePerDeviceAfterCashback: "49.99",
        finalPriceAfterCashback: "49.99",
        finalPriceAfterCashbackAfterDecimal: "99",
        pricePerYear: "49.99",
        finalPrice: "49.99",
        discountInPercent: "38",
        pricePerYearAfterCashback: "49.99",
        pricePerMonthAfterCashbackAfterDecimal: "16",
        pricePerMonthBeforeDecimal: "4",
        totalCashbackAfterDecimal: "00",
        totalCashbackBeforeDecimal: "0",
        pricePerYearAfterCashbackAfterDecimal: "99",
        aRPriceAfterDecimal: "99",
        discountValueAfterDecimal: "00",
        pricePerDayAfterDecimal: "13",
        pricePerDayBeforeDecimal: "0",
        pricePerDayAfterCashbackBeforeDecimal: "0",
        aRPriceBeforeDecimal: "79",
        discountAmountAfterCashbackBeforeDecimal: "30",
        finalPriceBeforeDecimal: "49",
        pricePerDeviceAfterCashbackAfterDecimal: "99",
        pricePerYearBeforeDecimal: "49",
        retailPriceBeforeDecimal: "79",
        pricePerDeviceBeforeDecimal: "49",
        pricePerDeviceAfterDecimal: "99",
        pricePerDay: "0.13",
        discountAmountAfterCashback: "30.00",
        retailPriceAfterDecimal: "99",
        discountValueBeforeDecimal: "30",
        pricePerDevice: "49.99",
        finalPriceAfterCashbackBeforeDecimal: "49",
        discountAmountAfterCashbackAfterDecimal: "00",
        pricePerDayAfterCashbackAfterDecimal: "13",
        totalCashback: "0.00",
        pricePerMonthAfterCashback: "4.16",
        pricePerDayAfterCashback: "0.13",
        pricePerMonthAfterCashbackBeforeDecimal: "4",
        retailPrice: "79.99",
        finalPriceAfterDecimal: "99",
        discountValue: "30",
        aRPrice: "79.99",
        pricePerDeviceAfterCashbackBeforeDecimal: "49",
      },
      metaOfferTypeValue: "Standard",
      discountType: 1,
      affiliateCode: "global_1262",
      metaOfferType: 1,
      aRPackagePlan: {
        unitOfMeasurement: 3,
        planType: 3,
        planTypeValue: "Renew",
        unitOfMeasurementValue: "Years",
        isAutoRenewable: false,
        unitValue: 1,
      },
      unitValue: 1,
      unitOfMeasurement: 3,
      cultureCode: "EN-CA",
      planType: 2,
      discountTypeValue: "Amount",
      promotionalARPrice: "",
      metaOfferGuid: "C7FD92B4-BF51-42B9-878E-5B26FF6347FF",
      pricePerDay: "C$0.13",
      discountAmountAfterCashback: "C$30.00",
      pricePerDevice: "C$49.99",
      planTypeValue: "Paid",
      packageCode: "mls_539",
      totalCashback: "C$0.00",
      pricePerMonthAfterCashback: "C$4.16",
      pricePerDayAfterCashback: "C$0.13",
      planDescription: "1-Years-Paid",
      isAutoRenewable: true,
      retailPrice: "C$79.99",
      currencyCode: "CAD",
      discountValue: "C$30.00",
      aRPrice: "C$79.99",
    },
    o5: {
      pricePerMonth: "C$2.91",
      pricePerDeviceAfterCashback: "C$69.99",
      finalPriceAfterCashback: "C$69.99",
      pricePerYear: "C$34.99",
      finalPrice: "C$69.99",
      discountInPercent: "56%",
      pricePerYearAfterCashback: "C$34.99",
      unitOfMeasurementValue: "Years",
      uf: {
        pricePerYearAfterCashbackBeforeDecimal: "34",
        pricePerYearAfterDecimal: "99",
        pricePerMonth: "2.91",
        pricePerMonthAfterDecimal: "91",
        pricePerDeviceAfterCashback: "69.99",
        finalPriceAfterCashback: "69.99",
        finalPriceAfterCashbackAfterDecimal: "99",
        pricePerYear: "34.99",
        finalPrice: "69.99",
        discountInPercent: "56",
        pricePerYearAfterCashback: "34.99",
        pricePerMonthAfterCashbackAfterDecimal: "91",
        pricePerMonthBeforeDecimal: "2",
        totalCashbackAfterDecimal: "00",
        totalCashbackBeforeDecimal: "0",
        pricePerYearAfterCashbackAfterDecimal: "99",
        aRPriceAfterDecimal: "99",
        discountValueAfterDecimal: "00",
        pricePerDayAfterDecimal: "09",
        pricePerDayBeforeDecimal: "0",
        pricePerDayAfterCashbackBeforeDecimal: "0",
        aRPriceBeforeDecimal: "79",
        discountAmountAfterCashbackBeforeDecimal: "90",
        finalPriceBeforeDecimal: "69",
        pricePerDeviceAfterCashbackAfterDecimal: "99",
        pricePerYearBeforeDecimal: "34",
        retailPriceBeforeDecimal: "159",
        pricePerDeviceBeforeDecimal: "69",
        pricePerDeviceAfterDecimal: "99",
        pricePerDay: "0.09",
        discountAmountAfterCashback: "90.00",
        retailPriceAfterDecimal: "99",
        discountValueBeforeDecimal: "90",
        pricePerDevice: "69.99",
        finalPriceAfterCashbackBeforeDecimal: "69",
        discountAmountAfterCashbackAfterDecimal: "00",
        pricePerDayAfterCashbackAfterDecimal: "09",
        totalCashback: "0.00",
        pricePerMonthAfterCashback: "2.91",
        pricePerDayAfterCashback: "0.09",
        pricePerMonthAfterCashbackBeforeDecimal: "2",
        retailPrice: "159.99",
        finalPriceAfterDecimal: "99",
        discountValue: "90",
        aRPrice: "79.99",
        pricePerDeviceAfterCashbackBeforeDecimal: "69",
      },
      metaOfferTypeValue: "Standard",
      discountType: 1,
      affiliateCode: "global_1262",
      metaOfferType: 1,
      aRPackagePlan: {
        unitOfMeasurement: 3,
        planType: 3,
        planTypeValue: "Renew",
        unitOfMeasurementValue: "Years",
        isAutoRenewable: false,
        unitValue: 1,
      },
      unitValue: 2,
      unitOfMeasurement: 3,
      cultureCode: "EN-CA",
      planType: 2,
      discountTypeValue: "Amount",
      promotionalARPrice: "",
      metaOfferGuid: "D5459BDB-E770-4746-9C30-4AF6278017FE",
      pricePerDay: "C$0.09",
      discountAmountAfterCashback: "C$90.00",
      pricePerDevice: "C$69.99",
      planTypeValue: "Paid",
      packageCode: "mls_539",
      totalCashback: "C$0.00",
      pricePerMonthAfterCashback: "C$2.91",
      pricePerDayAfterCashback: "C$0.09",
      planDescription: "2-Years-Paid",
      isAutoRenewable: true,
      retailPrice: "C$159.99",
      currencyCode: "CAD",
      discountValue: "C$90.00",
      aRPrice: "C$79.99",
    },
    o6: {
      pricePerMonth: "C$4.58",
      pricePerDeviceAfterCashback: "C$18.33",
      finalPriceAfterCashback: "C$54.99",
      pricePerYear: "C$54.99",
      finalPrice: "C$54.99",
      discountInPercent: "39%",
      pricePerYearAfterCashback: "C$54.99",
      unitOfMeasurementValue: "Years",
      uf: {
        pricePerYearAfterCashbackBeforeDecimal: "54",
        pricePerYearAfterDecimal: "99",
        pricePerMonth: "4.58",
        pricePerMonthAfterDecimal: "58",
        pricePerDeviceAfterCashback: "18.33",
        finalPriceAfterCashback: "54.99",
        finalPriceAfterCashbackAfterDecimal: "99",
        pricePerYear: "54.99",
        finalPrice: "54.99",
        discountInPercent: "39",
        pricePerYearAfterCashback: "54.99",
        pricePerMonthAfterCashbackAfterDecimal: "58",
        pricePerMonthBeforeDecimal: "4",
        totalCashbackAfterDecimal: "00",
        totalCashbackBeforeDecimal: "0",
        pricePerYearAfterCashbackAfterDecimal: "99",
        aRPriceAfterDecimal: "99",
        discountValueAfterDecimal: "00",
        pricePerDayAfterDecimal: "15",
        pricePerDayBeforeDecimal: "0",
        pricePerDayAfterCashbackBeforeDecimal: "0",
        aRPriceBeforeDecimal: "89",
        discountAmountAfterCashbackBeforeDecimal: "35",
        finalPriceBeforeDecimal: "54",
        pricePerDeviceAfterCashbackAfterDecimal: "33",
        pricePerYearBeforeDecimal: "54",
        retailPriceBeforeDecimal: "89",
        pricePerDeviceBeforeDecimal: "18",
        pricePerDeviceAfterDecimal: "33",
        pricePerDay: "0.15",
        discountAmountAfterCashback: "35.00",
        retailPriceAfterDecimal: "99",
        discountValueBeforeDecimal: "35",
        pricePerDevice: "18.33",
        finalPriceAfterCashbackBeforeDecimal: "54",
        discountAmountAfterCashbackAfterDecimal: "00",
        pricePerDayAfterCashbackAfterDecimal: "15",
        totalCashback: "0.00",
        pricePerMonthAfterCashback: "4.58",
        pricePerDayAfterCashback: "0.15",
        pricePerMonthAfterCashbackBeforeDecimal: "4",
        retailPrice: "89.99",
        finalPriceAfterDecimal: "99",
        discountValue: "35",
        aRPrice: "89.99",
        pricePerDeviceAfterCashbackBeforeDecimal: "18",
      },
      metaOfferTypeValue: "Standard",
      discountType: 1,
      affiliateCode: "global_1262",
      metaOfferType: 1,
      aRPackagePlan: {
        unitOfMeasurement: 3,
        planType: 3,
        planTypeValue: "Renew",
        unitOfMeasurementValue: "Years",
        isAutoRenewable: false,
        unitValue: 1,
      },
      unitValue: 1,
      unitOfMeasurement: 3,
      cultureCode: "EN-CA",
      planType: 2,
      discountTypeValue: "Amount",
      promotionalARPrice: "",
      metaOfferGuid: "2580B93C-E757-45C4-B92E-FF4DFBED3BDD",
      pricePerDay: "C$0.15",
      discountAmountAfterCashback: "C$35.00",
      pricePerDevice: "C$18.33",
      planTypeValue: "Paid",
      packageCode: "mls_540",
      totalCashback: "C$0.00",
      pricePerMonthAfterCashback: "C$4.58",
      pricePerDayAfterCashback: "C$0.15",
      planDescription: "1-Years-Paid",
      isAutoRenewable: true,
      retailPrice: "C$89.99",
      currencyCode: "CAD",
      discountValue: "C$35.00",
      aRPrice: "C$89.99",
    },
    o7: {
      pricePerMonth: "C$3.12",
      pricePerDeviceAfterCashback: "C$24.99",
      finalPriceAfterCashback: "C$74.99",
      pricePerYear: "C$37.49",
      finalPrice: "C$74.99",
      discountInPercent: "58%",
      pricePerYearAfterCashback: "C$37.49",
      unitOfMeasurementValue: "Years",
      uf: {
        pricePerYearAfterCashbackBeforeDecimal: "37",
        pricePerYearAfterDecimal: "49",
        pricePerMonth: "3.12",
        pricePerMonthAfterDecimal: "12",
        pricePerDeviceAfterCashback: "24.99",
        finalPriceAfterCashback: "74.99",
        finalPriceAfterCashbackAfterDecimal: "99",
        pricePerYear: "37.49",
        finalPrice: "74.99",
        discountInPercent: "58",
        pricePerYearAfterCashback: "37.49",
        pricePerMonthAfterCashbackAfterDecimal: "12",
        pricePerMonthBeforeDecimal: "3",
        totalCashbackAfterDecimal: "00",
        totalCashbackBeforeDecimal: "0",
        pricePerYearAfterCashbackAfterDecimal: "49",
        aRPriceAfterDecimal: "99",
        discountValueAfterDecimal: "00",
        pricePerDayAfterDecimal: "10",
        pricePerDayBeforeDecimal: "0",
        pricePerDayAfterCashbackBeforeDecimal: "0",
        aRPriceBeforeDecimal: "89",
        discountAmountAfterCashbackBeforeDecimal: "105",
        finalPriceBeforeDecimal: "74",
        pricePerDeviceAfterCashbackAfterDecimal: "99",
        pricePerYearBeforeDecimal: "37",
        retailPriceBeforeDecimal: "179",
        pricePerDeviceBeforeDecimal: "24",
        pricePerDeviceAfterDecimal: "99",
        pricePerDay: "0.10",
        discountAmountAfterCashback: "105.00",
        retailPriceAfterDecimal: "99",
        discountValueBeforeDecimal: "105",
        pricePerDevice: "24.99",
        finalPriceAfterCashbackBeforeDecimal: "74",
        discountAmountAfterCashbackAfterDecimal: "00",
        pricePerDayAfterCashbackAfterDecimal: "10",
        totalCashback: "0.00",
        pricePerMonthAfterCashback: "3.12",
        pricePerDayAfterCashback: "0.10",
        pricePerMonthAfterCashbackBeforeDecimal: "3",
        retailPrice: "179.99",
        finalPriceAfterDecimal: "99",
        discountValue: "105",
        aRPrice: "89.99",
        pricePerDeviceAfterCashbackBeforeDecimal: "24",
      },
      metaOfferTypeValue: "Standard",
      discountType: 1,
      affiliateCode: "global_1262",
      metaOfferType: 1,
      aRPackagePlan: {
        unitOfMeasurement: 3,
        planType: 3,
        planTypeValue: "Renew",
        unitOfMeasurementValue: "Years",
        isAutoRenewable: false,
        unitValue: 1,
      },
      unitValue: 2,
      unitOfMeasurement: 3,
      cultureCode: "EN-CA",
      planType: 2,
      discountTypeValue: "Amount",
      promotionalARPrice: "",
      metaOfferGuid: "59741F73-7667-4227-BA6C-50EDCE49C7BA",
      pricePerDay: "C$0.10",
      discountAmountAfterCashback: "C$105.00",
      pricePerDevice: "C$24.99",
      planTypeValue: "Paid",
      packageCode: "mls_540",
      totalCashback: "C$0.00",
      pricePerMonthAfterCashback: "C$3.12",
      pricePerDayAfterCashback: "C$0.10",
      planDescription: "2-Years-Paid",
      isAutoRenewable: true,
      retailPrice: "C$179.99",
      currencyCode: "CAD",
      discountValue: "C$105.00",
      aRPrice: "C$89.99",
    },
    o8: {
      pricePerMonth: "C$4.99",
      pricePerDeviceAfterCashback: "C$11.99",
      finalPriceAfterCashback: "C$59.99",
      pricePerYear: "C$59.99",
      finalPrice: "C$59.99",
      discountInPercent: "40%",
      pricePerYearAfterCashback: "C$59.99",
      unitOfMeasurementValue: "Years",
      uf: {
        pricePerYearAfterCashbackBeforeDecimal: "59",
        pricePerYearAfterDecimal: "99",
        pricePerMonth: "4.99",
        pricePerMonthAfterDecimal: "99",
        pricePerDeviceAfterCashback: "11.99",
        finalPriceAfterCashback: "59.99",
        finalPriceAfterCashbackAfterDecimal: "99",
        pricePerYear: "59.99",
        finalPrice: "59.99",
        discountInPercent: "40",
        pricePerYearAfterCashback: "59.99",
        pricePerMonthAfterCashbackAfterDecimal: "99",
        pricePerMonthBeforeDecimal: "4",
        totalCashbackAfterDecimal: "00",
        totalCashbackBeforeDecimal: "0",
        pricePerYearAfterCashbackAfterDecimal: "99",
        aRPriceAfterDecimal: "99",
        discountValueAfterDecimal: "00",
        pricePerDayAfterDecimal: "16",
        pricePerDayBeforeDecimal: "0",
        pricePerDayAfterCashbackBeforeDecimal: "0",
        aRPriceBeforeDecimal: "99",
        discountAmountAfterCashbackBeforeDecimal: "40",
        finalPriceBeforeDecimal: "59",
        pricePerDeviceAfterCashbackAfterDecimal: "99",
        pricePerYearBeforeDecimal: "59",
        retailPriceBeforeDecimal: "99",
        pricePerDeviceBeforeDecimal: "11",
        pricePerDeviceAfterDecimal: "99",
        pricePerDay: "0.16",
        discountAmountAfterCashback: "40.00",
        retailPriceAfterDecimal: "99",
        discountValueBeforeDecimal: "40",
        pricePerDevice: "11.99",
        finalPriceAfterCashbackBeforeDecimal: "59",
        discountAmountAfterCashbackAfterDecimal: "00",
        pricePerDayAfterCashbackAfterDecimal: "16",
        totalCashback: "0.00",
        pricePerMonthAfterCashback: "4.99",
        pricePerDayAfterCashback: "0.16",
        pricePerMonthAfterCashbackBeforeDecimal: "4",
        retailPrice: "99.99",
        finalPriceAfterDecimal: "99",
        discountValue: "40",
        aRPrice: "99.99",
        pricePerDeviceAfterCashbackBeforeDecimal: "11",
      },
      metaOfferTypeValue: "Standard",
      discountType: 1,
      affiliateCode: "global_1262",
      metaOfferType: 1,
      aRPackagePlan: {
        unitOfMeasurement: 3,
        planType: 3,
        planTypeValue: "Renew",
        unitOfMeasurementValue: "Years",
        isAutoRenewable: false,
        unitValue: 1,
      },
      unitValue: 1,
      unitOfMeasurement: 3,
      cultureCode: "EN-CA",
      planType: 2,
      discountTypeValue: "Amount",
      promotionalARPrice: "",
      metaOfferGuid: "6440C131-E3EF-49A4-B370-F39C3CE7743D",
      pricePerDay: "C$0.16",
      discountAmountAfterCashback: "C$40.00",
      pricePerDevice: "C$11.99",
      planTypeValue: "Paid",
      packageCode: "mls_541",
      totalCashback: "C$0.00",
      pricePerMonthAfterCashback: "C$4.99",
      pricePerDayAfterCashback: "C$0.16",
      planDescription: "1-Years-Paid",
      isAutoRenewable: true,
      retailPrice: "C$99.99",
      currencyCode: "CAD",
      discountValue: "C$40.00",
      aRPrice: "C$99.99",
    },
    o9: {
      pricePerMonth: "C$3.54",
      pricePerDeviceAfterCashback: "C$16.99",
      finalPriceAfterCashback: "C$84.99",
      pricePerYear: "C$42.49",
      finalPrice: "C$84.99",
      discountInPercent: "58%",
      pricePerYearAfterCashback: "C$42.49",
      unitOfMeasurementValue: "Years",
      uf: {
        pricePerYearAfterCashbackBeforeDecimal: "42",
        pricePerYearAfterDecimal: "49",
        pricePerMonth: "3.54",
        pricePerMonthAfterDecimal: "54",
        pricePerDeviceAfterCashback: "16.99",
        finalPriceAfterCashback: "84.99",
        finalPriceAfterCashbackAfterDecimal: "99",
        pricePerYear: "42.49",
        finalPrice: "84.99",
        discountInPercent: "58",
        pricePerYearAfterCashback: "42.49",
        pricePerMonthAfterCashbackAfterDecimal: "54",
        pricePerMonthBeforeDecimal: "3",
        totalCashbackAfterDecimal: "00",
        totalCashbackBeforeDecimal: "0",
        pricePerYearAfterCashbackAfterDecimal: "49",
        aRPriceAfterDecimal: "99",
        discountValueAfterDecimal: "00",
        pricePerDayAfterDecimal: "11",
        pricePerDayBeforeDecimal: "0",
        pricePerDayAfterCashbackBeforeDecimal: "0",
        aRPriceBeforeDecimal: "99",
        discountAmountAfterCashbackBeforeDecimal: "115",
        finalPriceBeforeDecimal: "84",
        pricePerDeviceAfterCashbackAfterDecimal: "99",
        pricePerYearBeforeDecimal: "42",
        retailPriceBeforeDecimal: "199",
        pricePerDeviceBeforeDecimal: "16",
        pricePerDeviceAfterDecimal: "99",
        pricePerDay: "0.11",
        discountAmountAfterCashback: "115.00",
        retailPriceAfterDecimal: "99",
        discountValueBeforeDecimal: "115",
        pricePerDevice: "16.99",
        finalPriceAfterCashbackBeforeDecimal: "84",
        discountAmountAfterCashbackAfterDecimal: "00",
        pricePerDayAfterCashbackAfterDecimal: "11",
        totalCashback: "0.00",
        pricePerMonthAfterCashback: "3.54",
        pricePerDayAfterCashback: "0.11",
        pricePerMonthAfterCashbackBeforeDecimal: "3",
        retailPrice: "199.99",
        finalPriceAfterDecimal: "99",
        discountValue: "115",
        aRPrice: "99.99",
        pricePerDeviceAfterCashbackBeforeDecimal: "16",
      },
      metaOfferTypeValue: "Standard",
      discountType: 1,
      affiliateCode: "global_1262",
      metaOfferType: 1,
      aRPackagePlan: {
        unitOfMeasurement: 3,
        planType: 3,
        planTypeValue: "Renew",
        unitOfMeasurementValue: "Years",
        isAutoRenewable: false,
        unitValue: 1,
      },
      unitValue: 2,
      unitOfMeasurement: 3,
      cultureCode: "EN-CA",
      planType: 2,
      discountTypeValue: "Amount",
      promotionalARPrice: "",
      metaOfferGuid: "1EE5E441-2870-4512-BB8C-E46D76A9C3DF",
      pricePerDay: "C$0.11",
      discountAmountAfterCashback: "C$115.00",
      pricePerDevice: "C$16.99",
      planTypeValue: "Paid",
      packageCode: "mls_541",
      totalCashback: "C$0.00",
      pricePerMonthAfterCashback: "C$3.54",
      pricePerDayAfterCashback: "C$0.11",
      planDescription: "2-Years-Paid",
      isAutoRenewable: true,
      retailPrice: "C$199.99",
      currencyCode: "CAD",
      discountValue: "C$115.00",
      aRPrice: "C$99.99",
    },
    o11: {
      pricePerMonth: "C$3.74",
      pricePerDeviceAfterCashback: "C$1.79",
      finalPriceAfterCashback: "C$89.99",
      pricePerYear: "C$44.99",
      finalPrice: "C$89.99",
      discountInPercent: "63%",
      pricePerYearAfterCashback: "C$44.99",
      unitOfMeasurementValue: "Years",
      uf: {
        pricePerYearAfterCashbackBeforeDecimal: "44",
        pricePerYearAfterDecimal: "99",
        pricePerMonth: "3.74",
        pricePerMonthAfterDecimal: "74",
        pricePerDeviceAfterCashback: "1.79",
        finalPriceAfterCashback: "89.99",
        finalPriceAfterCashbackAfterDecimal: "99",
        pricePerYear: "44.99",
        finalPrice: "89.99",
        discountInPercent: "63",
        pricePerYearAfterCashback: "44.99",
        pricePerMonthAfterCashbackAfterDecimal: "74",
        pricePerMonthBeforeDecimal: "3",
        totalCashbackAfterDecimal: "00",
        totalCashbackBeforeDecimal: "0",
        pricePerYearAfterCashbackAfterDecimal: "99",
        aRPriceAfterDecimal: "99",
        discountValueAfterDecimal: "00",
        pricePerDayAfterDecimal: "12",
        pricePerDayBeforeDecimal: "0",
        pricePerDayAfterCashbackBeforeDecimal: "0",
        aRPriceBeforeDecimal: "119",
        discountAmountAfterCashbackBeforeDecimal: "150",
        finalPriceBeforeDecimal: "89",
        pricePerDeviceAfterCashbackAfterDecimal: "79",
        pricePerYearBeforeDecimal: "44",
        retailPriceBeforeDecimal: "239",
        pricePerDeviceBeforeDecimal: "1",
        pricePerDeviceAfterDecimal: "79",
        pricePerDay: "0.12",
        discountAmountAfterCashback: "150.00",
        retailPriceAfterDecimal: "99",
        discountValueBeforeDecimal: "150",
        pricePerDevice: "1.79",
        finalPriceAfterCashbackBeforeDecimal: "89",
        discountAmountAfterCashbackAfterDecimal: "00",
        pricePerDayAfterCashbackAfterDecimal: "12",
        totalCashback: "0.00",
        pricePerMonthAfterCashback: "3.74",
        pricePerDayAfterCashback: "0.12",
        pricePerMonthAfterCashbackBeforeDecimal: "3",
        retailPrice: "239.99",
        finalPriceAfterDecimal: "99",
        discountValue: "150",
        aRPrice: "119.99",
        pricePerDeviceAfterCashbackBeforeDecimal: "1",
      },
      metaOfferTypeValue: "Standard",
      discountType: 1,
      affiliateCode: "global_1262",
      metaOfferType: 1,
      aRPackagePlan: {
        unitOfMeasurement: 3,
        planType: 3,
        planTypeValue: "Renew",
        unitOfMeasurementValue: "Years",
        isAutoRenewable: false,
        unitValue: 1,
      },
      unitValue: 2,
      unitOfMeasurement: 3,
      cultureCode: "EN-CA",
      planType: 2,
      discountTypeValue: "Amount",
      promotionalARPrice: "",
      metaOfferGuid: "1E250D49-E473-4085-9175-D799E4DDC31E",
      pricePerDay: "C$0.12",
      discountAmountAfterCashback: "C$150.00",
      pricePerDevice: "C$1.79",
      planTypeValue: "Paid",
      packageCode: "mls_430",
      totalCashback: "C$0.00",
      pricePerMonthAfterCashback: "C$3.74",
      pricePerDayAfterCashback: "C$0.12",
      planDescription: "2-Years-Paid",
      isAutoRenewable: true,
      retailPrice: "C$239.99",
      currencyCode: "CAD",
      discountValue: "C$150.00",
      aRPrice: "C$119.99",
    },
    o10: {
      pricePerMonth: "C$4.99",
      pricePerDeviceAfterCashback: "C$1.19",
      finalPriceAfterCashback: "C$59.99",
      pricePerYear: "C$59.99",
      finalPrice: "C$59.99",
      discountInPercent: "50%",
      pricePerYearAfterCashback: "C$59.99",
      unitOfMeasurementValue: "Years",
      uf: {
        pricePerYearAfterCashbackBeforeDecimal: "59",
        pricePerYearAfterDecimal: "99",
        pricePerMonth: "4.99",
        pricePerMonthAfterDecimal: "99",
        pricePerDeviceAfterCashback: "1.19",
        finalPriceAfterCashback: "59.99",
        finalPriceAfterCashbackAfterDecimal: "99",
        pricePerYear: "59.99",
        finalPrice: "59.99",
        discountInPercent: "50",
        pricePerYearAfterCashback: "59.99",
        pricePerMonthAfterCashbackAfterDecimal: "99",
        pricePerMonthBeforeDecimal: "4",
        totalCashbackAfterDecimal: "00",
        totalCashbackBeforeDecimal: "0",
        pricePerYearAfterCashbackAfterDecimal: "99",
        aRPriceAfterDecimal: "99",
        discountValueAfterDecimal: "00",
        pricePerDayAfterDecimal: "16",
        pricePerDayBeforeDecimal: "0",
        pricePerDayAfterCashbackBeforeDecimal: "0",
        aRPriceBeforeDecimal: "119",
        discountAmountAfterCashbackBeforeDecimal: "60",
        finalPriceBeforeDecimal: "59",
        pricePerDeviceAfterCashbackAfterDecimal: "19",
        pricePerYearBeforeDecimal: "59",
        retailPriceBeforeDecimal: "119",
        pricePerDeviceBeforeDecimal: "1",
        pricePerDeviceAfterDecimal: "19",
        pricePerDay: "0.16",
        discountAmountAfterCashback: "60.00",
        retailPriceAfterDecimal: "99",
        discountValueBeforeDecimal: "60",
        pricePerDevice: "1.19",
        finalPriceAfterCashbackBeforeDecimal: "59",
        discountAmountAfterCashbackAfterDecimal: "00",
        pricePerDayAfterCashbackAfterDecimal: "16",
        totalCashback: "0.00",
        pricePerMonthAfterCashback: "4.99",
        pricePerDayAfterCashback: "0.16",
        pricePerMonthAfterCashbackBeforeDecimal: "4",
        retailPrice: "119.99",
        finalPriceAfterDecimal: "99",
        discountValue: "60",
        aRPrice: "119.99",
        pricePerDeviceAfterCashbackBeforeDecimal: "1",
      },
      metaOfferTypeValue: "Standard",
      discountType: 1,
      affiliateCode: "global_1262",
      metaOfferType: 1,
      aRPackagePlan: {
        unitOfMeasurement: 3,
        planType: 3,
        planTypeValue: "Renew",
        unitOfMeasurementValue: "Years",
        isAutoRenewable: false,
        unitValue: 1,
      },
      unitValue: 1,
      unitOfMeasurement: 3,
      cultureCode: "EN-CA",
      planType: 2,
      discountTypeValue: "Amount",
      promotionalARPrice: "",
      metaOfferGuid: "AF4ADF40-C58E-40EE-B9FE-240DE3A28DDB",
      pricePerDay: "C$0.16",
      discountAmountAfterCashback: "C$60.00",
      pricePerDevice: "C$1.19",
      planTypeValue: "Paid",
      packageCode: "mls_430",
      totalCashback: "C$0.00",
      pricePerMonthAfterCashback: "C$4.99",
      pricePerDayAfterCashback: "C$0.16",
      planDescription: "1-Years-Paid",
      isAutoRenewable: true,
      retailPrice: "C$119.99",
      currencyCode: "CAD",
      discountValue: "C$60.00",
      aRPrice: "C$119.99",
    },
  },
  cacheableQSParams: [],
  cacheableDependentQSParams: [],
  utagEvent: {
    config: [
      {
        fired: "false",
        pageLoad: "false",
        defaultValue: "true",
        fireWhen: "na",
        fireCount: "multiple",
        tagName: "tm_global_buynow_clicks",
        type: "individual",
        timesFired: "0",
      },
    ],
  },
  payments: {
    culturePayments: {
      100: {
        paymentFee: 0,
        methods: {
          1: {
            hideCvv: false,
            hideIcon: false,
            typeName: "VISA",
            format: ["^4[0-9]{12}(?:[0-9]{3})?$", "^4"],
            icon: "",
            type: "100",
            title: "VISA",
            iconAltText: "",
            isActiveMethod: true,
            ccLength: "16",
            bankCodeName: "",
            typeId: "1",
            typeValue: "CreditCard",
            netBankingOrder: "-1",
            cfPath: "credit-cards/visa",
            cvvLength: "3",
          },
          2: {
            hideCvv: false,
            hideIcon: false,
            typeName: "MASTERCARD",
            format: ["^2[0-9]{15}$|^5[1-5][0-9]{14}$", "^2[0-9]|^5[1-5]"],
            icon: "",
            type: "100",
            title: "MASTER CARD",
            iconAltText: "",
            isActiveMethod: true,
            ccLength: "16",
            bankCodeName: "",
            typeId: "2",
            typeValue: "CreditCard",
            netBankingOrder: "-1",
            cfPath: "credit-cards/mastercard",
            cvvLength: "3",
          },
          3: {
            hideCvv: false,
            hideIcon: false,
            typeName: "AMERICAN EXPRESS",
            format: ["^3[4,7]\\d{13}$", "^3[4,7]"],
            icon: "",
            type: "100",
            title: "AMERICAN EXPRESS",
            iconAltText: "Amex",
            isActiveMethod: true,
            ccLength: "15",
            bankCodeName: "",
            typeId: "3",
            typeValue: "CreditCard",
            netBankingOrder: "-1",
            cfPath: "credit-cards/american-express",
            cvvLength: "4",
          },
        },
        icon: "",
        title: "Credit card",
        iconAltText: "",
        hideOnZeroPrice: false,
        isAREnabled: true,
        bankList: {},
        isActivePayment: true,
        typeId: "100",
        typeValue: "CreditCard",
        cfPath: "creditcardgroup",
        isGroup: false,
      },
      101: {
        paymentFee: 0,
        methods: {},
        icon: "/content/dam/consumer/en-us/payment-icons/logo_paypal.png",
        title: "PayPal",
        iconAltText: "PayPal",
        hideOnZeroPrice: true,
        isAREnabled: true,
        bankList: {},
        isActivePayment: true,
        typeId: "101",
        typeValue: "PayPal",
        cfPath: "paypal",
        isGroup: true,
      },
    },
    others: {
      100: {
        paymentFee: 0,
        methods: {
          1: {
            hideCvv: false,
            hideIcon: false,
            typeName: "VISA",
            format: ["^4[0-9]{12}(?:[0-9]{3})?$", "^4"],
            icon: "",
            type: "100",
            title: "VISA",
            iconAltText: "",
            isActiveMethod: true,
            ccLength: "16",
            bankCodeName: "",
            typeId: "1",
            typeValue: "CreditCard",
            netBankingOrder: "-1",
            cfPath: "credit-cards/visa",
            cvvLength: "3",
          },
          2: {
            hideCvv: false,
            hideIcon: false,
            typeName: "MASTERCARD",
            format: ["^2[0-9]{15}$|^5[1-5][0-9]{14}$", "^2[0-9]|^5[1-5]"],
            icon: "",
            type: "100",
            title: "MASTER CARD",
            iconAltText: "",
            isActiveMethod: true,
            ccLength: "16",
            bankCodeName: "",
            typeId: "2",
            typeValue: "CreditCard",
            netBankingOrder: "-1",
            cfPath: "credit-cards/mastercard",
            cvvLength: "3",
          },
        },
        icon: "",
        title: "Credit card",
        iconAltText: "",
        hideOnZeroPrice: false,
        isAREnabled: true,
        bankList: {},
        isActivePayment: true,
        typeId: "100",
        typeValue: "CreditCard",
        cfPath: "creditcardgroup",
        isGroup: false,
      },
    },
  },
  cacheableDependentDataLayers: [],
  cacheableDataLayers: ["affiliateV2"],
  tealiumSettings: {
    config: {
      environmentPath: "mcafee/consumer-main/qa",
      synchronousConnection: false,
      fireAnalytics: true,
      loadInterval: "1500",
    },
  },
  utagFetch: {
    config: [
      {
        tagName: "tm_global_affiliate_code",
        config: "digitalData.affiliate.affUrlCode",
      },
      {
        tagName: "tm_global_affiliate_id",
        config: "digitalData.affiliate.affid",
      },
      {
        tagName: "tm_global_affiliate_name",
        config: "digitalData.affiliate.affname",
      },
      {
        tagName: "tm_global_channel",
        config: "digitalData.affiliate.channel",
      },
      {
        tagName: "tm_global_country",
        config: "digitalData.culture.country",
      },
      {
        tagName: "tm_global_culture_code",
        config: "digitalData.culture.culture",
      },
      {
        tagName: "tm_global_geo",
        config: "digitalData.culture.geo",
      },
      {
        tagName: "tm_global_businessunit",
        config: "digitalData.analytics.businessUnit",
      },
      {
        tagName: "tm_global_platform",
        config: "digitalData.analytics.platform",
      },
      {
        tagName: "tm_global_source_type",
        config: "digitalData.analytics.sourceType",
      },
      {
        tagName: "tm_global_traffic_source_type",
        config: "digitalData.analytics.trafficSourceType",
      },
      {
        tagName: "tm_global_sitesection",
        config: "digitalData.analytics.siteSection",
      },
      {
        tagName: "tm_global_sitesection_level2",
        config: "digitalData.analytics.siteSectionLevel2",
      },
      {
        tagName: "tm_global_sitesection_level3",
        config: "digitalData.analytics.siteSectionLevel3",
      },
      {
        tagName: "tm_global_3rdparty_pixels",
        config: "digitalData.analytics['3rdPartyPixels']",
      },
      {
        tagName: "tm_global_page_publish_date",
        config: "digitalData.page.publishDate",
      },
      {
        tagName: "tm_global_vanity_url",
        config: "digitalData.page.vanityURL",
      },
      {
        tagName: "tm_global_pagename",
        config: "digitalData.page.name",
      },
      {
        tagName: "tm_global_pageurl",
        config: "digitalData.page.url + window.location.search",
      },
      {
        tagName: "tm_global_purchase_product_codes",
        config:
          "Object.values(window.digitalData.offers).map(function(off){return off.packageCode}).filter(function(value, index, self) {return self.indexOf(value) === index;}).join(',')",
      },
      {
        tagName: "tm_global_purchase_product_ids",
        config:
          "Object.values(window.digitalData.offers).map(function(off){return off.packageCode.split('_')[1]}).filter(function(value, index, self) {return self.indexOf(value) === index;}).join(',')",
      },
      {
        tagName: "tm_global_cms_experience_name",
        config:
          "digitalData.experiences.selectedExperiences ? Object.values(digitalData.experiences.selectedExperiences).map(function(exp){return exp.experienceTitle}).join(',').replaceDash() :''",
      },
      {
        tagName: "tm_global_cms_segment",
        config:
          "var rule = window.digitalData.offerSegmentRules.rules.filter(function(ex) { return ex.evalResult == true})[0]; rule && rule.name ? rule.name.toLowerCase().replaceDash() : '';",
      },
      {
        tagName: "tm_global_cms_campaign_p_name",
        config: "analyticsData.getCampaignPName()",
      },
      {
        tagName: "tm_global_cms_campaign_pu_name",
        config: "analyticsData.getCampaignPUName()",
      },
      {
        tagName: "tm_global_coe",
        config:
          "digitalData.qs.ccoe ? digitalData.qs.ccoe : digitalData.analytics.coe",
      },
      {
        tagName: "tm_global_coe_level2",
        config:
          "digitalData.qs.ccoel2 ? digitalData.qs.ccoel2 : digitalData.analytics.coel2",
      },
      {
        tagName: "tm_global_cms_campaign_type",
        config:
          "digitalData.qs.cctype ? digitalData.qs.cctype : digitalData.analytics.campaignType",
      },
      {
        tagName: "tm_global_cms_campaign_sub_type",
        config:
          "digitalData.qs.ccstype ? digitalData.qs.ccstype : digitalData.analytics.campaignSubType",
      },
      {
        tagName: "tm_global_source",
        config:
          "digitalData.qs.csrc ? digitalData.qs.csrc : analyticsData.getGlobalSource()",
      },
      {
        tagName: "tm_global_source_level2",
        config:
          "digitalData.qs.csrcl2 ? digitalData.qs.csrcl2 : analyticsData.getSourceLevel2()",
      },
      {
        tagName: "tm_global_affiliate_category",
        config: "digitalData.qs.cafcat",
      },
      {
        tagName: "tm_global_loginstatus",
        config:
          "(function getLoginStatus(){switch(digitalData.qs.cls){case '1':return'unauthenticated : new';case '2':return'authenticated : new';case '3':return'authenticated : existing';case '4':return'unauthenticated: existing';default:return'unknown'}})()",
      },
      {
        tagName: "tm_global_cms_targeted_user_profile",
        config:
          "var rule = window.digitalData.offerSegmentRules.rules.filter(function(ex) { return ex.evalResult == true})[0]; digitalData.qs.cseg ? digitalData.qs.cseg : rule && rule.name ? rule.name.toLowerCase().replaceDash() : ''",
      },
      {
        tagName: "tm_global_user_profile_type1",
        config:
          "(function getUserProfileType1(){switch(digitalData.qs.cupf){case '1':return'new';case '2':return'cof';case '3':return'noncof';default:return'notfound'}})()",
      },
      {
        tagName: "tm_global_ak_culture",
        config: "digitalData.qs.ak_culture",
      },
      {
        tagName: "tm_global_ip_state",
        config: "digitalData.qs.ipst",
      },
      {
        tagName: "tm_global_ip_country",
        config: "digitalData.qs.ipcon",
      },
      {
        tagName: "tm_local_lp_ab_test_variant",
        config: "digitalData.qs.tm_local_lp_ab_test_variant",
      },
      {
        defaultValue: "",
        tagName: "tm_global_navigation_element",
      },
      {
        defaultValue: "",
        tagName: "tm_global_cms_campaign_pub_name",
      },
      {
        defaultValue: "true",
        tagName: "tm_global_navigation_element_click",
      },
      {
        tagName: "tm_local_store_page_visit",
        config:
          "digitalData.analytics.siteSection && digitalData.analytics.siteSection.toLowerCase() == 'store' ? true : false",
      },
      {
        tagName: "tm_local_landing_page_visit",
        config:
          "digitalData.analytics.siteSection && digitalData.analytics.siteSection.toLowerCase() == 'landingpages' ? true : false",
      },
    ],
    order: ["config"],
  },
  experiences: {
    totalSections: 4,
    sections: [
      {
        path:
          "/content/consumer/en-ca/landing-page/retention/mls-family/livesafe3-01/jcr:content/root/responsivegrid/offerconfig",
        personalized: false,
      },
      {
        path:
          "/content/consumer/en-ca/landing-page/retention/mls-family/livesafe3-01/jcr:content/root/responsivegrid/htmlcontentfragment_",
        personalized: false,
      },
      {
        path:
          "/content/consumer/en-ca/landing-page/retention/mls-family/livesafe3-01/jcr:content/root/responsivegrid/personalizedsection",
        personalized: false,
      },
      {
        path:
          "/content/consumer/en-ca/landing-page/retention/mls-family/livesafe3-01/jcr:content/root/responsivegrid/personalizedsection_",
        personalized: false,
      },
    ],
  },
  cart: {
    cartUrl: "/consumer/en-ca/ipz/checkout/2web/payment.html",
  },
  analytics: {
    siteSection: "landingpages",
    businessUnit: "Consumer",
    campaignType: "expiry",
    campaignSubType: "default",
    sourceType: "client:wss:tp:buy",
    trafficSourceType: "expiry",
    siteSectionLevel3: "expiry",
    siteSectionLevel2: "atp",
    platform: "web",
  },
  nonCacheableQSParams: [],
  culture: {
    geo: "na",
    continent: "AS",
    country: "canada",
    culture: "en-ca",
    countryCode: "IN",
    currencyCode: "cad",
  },
  page: {
    applicationType: "",
    publishDate: "date: 30/4/2021 time: 5:50:18 timezone: gmt-07:00",
    rules: [
      {
        expression:
          "(digitalData.subscription && (digitalData.subscription.termtype == 1 || digitalData.subscription.termtype == 0 || digitalData.subscription.daysToExpire > 0 || (digitalData.subscription.daysToExpire == 0 && digitalData.subscription.daysExpired == 0)))",
        assignment: "(digitalData.page.title='McAfee LiveSafe - Expires Soon')",
      },
      {
        expression:
          "(digitalData.subscription && (digitalData.subscription.termtype == 2 || digitalData.subscription.daysExpired > 0))",
        assignment: "(digitalData.page.title='McAfee LiveSafe - Expired')",
      },
    ],
    title: "livesafe3-0",
    path:
      "/content/consumer/en-ca/landing-page/retention/mls-family/livesafe3-01",
    subscriptionExtn: "false",
    instanceId: "livesafe3-01",
    isSessionDataEnabled: false,
    piiData: ["email"],
    vanityURL: "not available",
    cartType: "single",
    lang: "en_CA",
    navTitle: "livesafe3-0",
    disableProcessTaxCall: "false",
    themeCSS: "inherit",
    effectiveCSS: "",
    langTag: "en-CA",
    setCheckoutSessionCookie: "false",
    url:
      "http://mcafee-uat.mcafee.com/content/consumer/en-ca/landing-page/retention/mls-family/livesafe3-01.html",
    actionType: "savebillingwithARturnON",
    isAuthorMode: false,
    name: "livesafe3-01",
    overrideCSS: false,
    wcmMode: "DISABLED",
    flowType: "",
  },
  utagView: {
    config: [
      {
        tagName: "tm_global_affiliate_code",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_affiliate_id",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_affiliate_name",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_channel",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_country",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_culture_code",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_geo",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_businessunit",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_platform",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_source_type",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_traffic_source_type",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_sitesection",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_sitesection_level2",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_sitesection_level3",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_3rdparty_pixels",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_page_publish_date",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_vanity_url",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_pagename",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_pageurl",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_purchase_product_codes",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_purchase_product_ids",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_cms_experience_name",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_cms_segment",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_cms_campaign_p_name",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_cms_campaign_pu_name",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_global_coe",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_coe_level2",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_cms_campaign_type",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_cms_campaign_sub_type",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_source",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_source_level2",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_affiliate_category",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_loginstatus",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_cms_targeted_user_profile",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_user_profile_type1",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_ak_culture",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_ip_state",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_global_ip_country",
        event: "all",
        pageView: "true",
      },
      {
        tagName: "tm_local_lp_ab_test_variant",
        event: "all",
        pageView: "true",
      },
      {
        specificEvents: ["tm_global_buynow_clicks"],
        tagName: "tm_global_navigation_element",
        event: "specificEvents",
        pageView: "false",
      },
      {
        specificEvents: ["tm_global_buynow_clicks"],
        tagName: "tm_global_cms_campaign_pub_name",
        event: "specificEvents",
        pageView: "false",
      },
      {
        specificEvents: ["tm_global_buynow_clicks"],
        tagName: "tm_global_navigation_element_click",
        event: "specificEvents",
        pageView: "false",
      },
      {
        tagName: "tm_local_store_page_visit",
        event: "none",
        pageView: "true",
      },
      {
        tagName: "tm_local_landing_page_visit",
        event: "none",
        pageView: "true",
      },
    ],
  },
  nonCacheableDataLayers: [
    "geoData",
    "deviceV2",
    "orderV2",
    "userProfileV2",
    "subscriptionV2",
    "cookie",
  ],
};
